import type { Metadata } from 'next'
import { MantineProvider, BackgroundImage } from '@mantine/core'
import SocketProvider from '@/context/socketContext'
import './globals.css'
import '@mantine/core/styles.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body>
        <MantineProvider defaultColorScheme="dark">
          <BackgroundImage
            src="https://wallpapers.com/images/featured/dark-theme-background-q62o6998n8bqxzrf.jpg"
            h={'100vh'}
            w={'100vw'}
          >
            <SocketProvider>
                {children}
            </SocketProvider>
          </BackgroundImage>
        </MantineProvider>
      </body>
    </html>
  )
}
